services:
  database_orders:
    image: postgres:alpine
    container_name: database_orders
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    networks:
      - orders_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

  orders_service:
    container_name: orders-management-services
    build:
      context: ./orders-management
      dockerfile: Dockerfile
    image: orders_service:1.0
    depends_on:
      database_orders:
        condition: service_healthy
    networks:
      - orders_network
    ports:
      - "5001:5001"
    restart: always

networks:
  orders_network:
    driver: bridge