name: Build and Deploy Docker Image

on:
  workflow_dispatch: # Permite la ejecución manual

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Get Cloud SQL Instance Private IP
        id: get_ip
        run: |
          IP=$(gcloud sql instances describe postgres --format="value(ipAddresses.ipAddress[type=PRIVATE])")
          echo "::set-output name=db_ip::$IP"

      - name: Update ./orders-management/src/.env.development
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          sed -i "s/DB_HOST=localhost/DB_HOST=${{ steps.get_ip.outputs.db_ip }}/g" ./orders-management/src/.env.development

      - name: Show updated .env.development
        run: |
          echo "Updated .env.development content:"
          cat ./orders-management/src/.env.development

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/proyecto-final-451719/proyecto/orders-management-image:latest ./orders-management
          docker push us-central1-docker.pkg.dev/proyecto-final-451719/proyecto/orders-management-image:latest