name: Build and Deploy Docker Image

on:
  workflow_dispatch: # Permite la ejecución manual

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Get Cloud SQL Instance Private IP
        id: get_ip
        run: |

          echo "Obteniendo las IPs de la instancia..."
          IP_ADDRESSES=$(gcloud sql instances describe postgres --format="value(ipAddresses)")

          if [ -z "$IP_ADDRESSES" ]; then
            echo "Error: No se encontraron IPs para la instancia."
            exit 1
          fi

          echo "Extrayendo la IP privada..."
          PRIVATE_IP=$(echo "$IP_ADDRESSES" | grep -oP "'ipAddress': '\K[0-9.]+(?=', 'type': 'PRIVATE')")

          # Verifica si se encontró una IP privada
          if [ -z "$PRIVATE_IP" ]; then
            echo "Error: No se pudo obtener la IP privada."
            echo "IPs encontradas: $IP_ADDRESSES"
            exit 1
          fi

          echo "IP privada: $PRIVATE_IP"
          echo "::set-output name=db_ip::$PRIVATE_IP"

      - name: Update ./orders-management/src/.env.development
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          sed -i "s/DB_HOST=localhost/DB_HOST=${{ steps.get_ip.outputs.db_ip }}/g" ./orders-management/src/.env.development

      - name: Update ./products-management/src/.env.development
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          sed -i "s/DB_HOST=localhost/DB_HOST=${{ steps.get_ip.outputs.db_ip }}/g" ./products-management/src/.env.development

            
      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image Orders
        run: |
          docker build -t us-central1-docker.pkg.dev/proyecto-final-451719/proyecto/orders-management-image:latest ./orders-management
          docker push us-central1-docker.pkg.dev/proyecto-final-451719/proyecto/orders-management-image:latest

      - name: Build and Push Docker Image Products
        run: |
          docker build -t us-central1-docker.pkg.dev/proyecto-final-451719/proyecto/products-management-image:latest ./products-management
          docker push us-central1-docker.pkg.dev/proyecto-final-451719/proyecto/products-management-image:latest