name: Delete Resources

on:
  workflow_dispatch: # Permite la ejecución manual

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Delete Cloud SQL Instance
        run: |
          gcloud sql instances delete postgres --quiet

      - name: Delete Cloud Run Service
        run: |
          gcloud run services delete orders-management-service --region=us-central1 --platform=managed --quiet

      - name: Delete Docker Image
        run: |
          gcloud artifacts docker images delete us-central1-docker.pkg.dev/proyecto-final-451719/proyecto/orders-management-image:latest --quiet
