name: Delete Resources

on:
  workflow_dispatch: # Permite la ejecución manual

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Delete Cloud SQL Instance
        run: |
          gcloud sql instances delete postgres --quiet

      - name: Delete Cloud Run Service (Orders Management)
        run: |
          gcloud run services delete orders-management-service --region=us-central1 --platform=managed --quiet

      - name: Delete Cloud Run Service (Products Management)
        run: |
          gcloud run services delete products-management-service --region=us-central1 --platform=managed --quiet

      - name: Delete Cloud Run Service (Authentications Management)
        run: |
          gcloud run services delete authentications_management-service --region=us-central1 --platform=managed --quiet

      - name: Delete Cloud Run Service (Manufacturers Management)
        run: |
          gcloud run services delete manufacturers-management-service --region=us-central1 --platform=managed --quiet

      - name: Delete Cloud Run Service (Customers Management)
        run: |
          gcloud run services delete customers-management-service --region=us-central1 --platform=managed --quiet

      - name: Delete Cloud Run Service (AI Services)
        run: |
          gcloud run services delete ai-services --region=us-central1 --platform=managed --quiet

      - name: Delete Cloud Run Service (NGINX)
        run: |
          gcloud run services delete nginx-service --region=us-central1 --platform=managed --quiet

      - name: Delete Docker Image (Orders Management)
        run: |
          gcloud artifacts docker images delete us-central1-docker.pkg.dev/proyecto-final-451719/proyecto/orders-management-image:latest --quiet

      - name: Delete Docker Image (Products Management)
        run: |
          gcloud artifacts docker images delete us-central1-docker.pkg.dev/proyecto-final-451719/proyecto/products-management-image:latest --quiet

      - name: Delete Docker Image (Authentications Management)
        run: |
          gcloud artifacts docker images delete us-central1-docker.pkg.dev/proyecto-final-451719/proyecto/authentications_management-image:latest --quiet
      
      - name: Delete Docker Image (Manufacturers Management)
        run: |
          gcloud artifacts docker images delete us-central1-docker.pkg.dev/proyecto-final-451719/proyecto/manufacturers-management-image:latest --quiet
      
      - name: Delete Docker Image (Customers Management)
        run: |
          gcloud artifacts docker images delete us-central1-docker.pkg.dev/proyecto-final-451719/proyecto/customers-management-image:latest --quiet
      
      - name: Delete Docker Image (AI Services)
        run: |
          gcloud artifacts docker images delete us-central1-docker.pkg.dev/proyecto-final-451719/proyecto/ai-services-image:latest --quiet
          
      - name: Delete Docker Image (NGINX)
        run: |
          gcloud artifacts docker images delete us-central1-docker.pkg.dev/proyecto-final-451719/proyecto/nginx-image:latest --quiet

      - name: Delete VPC Access Connector (Orders Management)
        run: |
          gcloud compute networks vpc-access connectors delete orders-vpc-connector --region=us-central1 --quiet