name: Deploy to Cloud Run

on:
  workflow_dispatch: # Permite la ejecución manual

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Enable Serverless VPC Access API
        run: |
          gcloud services enable vpcaccess.googleapis.com

      - name: Create VPC Access Connector
        id: create_vpc_connector
        run: |
          # Verifica si el VPC Connector ya existe
          if ! gcloud compute networks vpc-access connectors describe orders-vpc-connector --region=us-central1 > /dev/null 2>&1; then
            echo "Creando VPC Connector..."
            gcloud compute networks vpc-access connectors create orders-vpc-connector \
              --region=us-central1 \
              --network=default \
              --range=10.8.0.0/28
          else
            echo "El VPC Connector ya existe. Saltando creación."
          fi

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy orders-management-service \
            --image=us-central1-docker.pkg.dev/proyecto-final-451719/proyecto/orders-management-image:latest \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated \
            --memory=512Mi \
            --cpu=1 \
            --concurrency=80 \
            --port=5001 \
            --vpc-connector=orders-vpc-connector \
            --egress-settings=private-ranges-only