name: Master Workflow

on:
  workflow_dispatch:

jobs:
  trigger_workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deploy DB Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: deploy-cloud-sql.yml
          token: ${{ secrets.PAT_TOKEN }}

      - name: Wait for Deploy DB Workflow
        run: sleep 390

      - name: Trigger Build and Deploy Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-and-deploy.yml
          token: ${{ secrets.PAT_TOKEN }}

      - name: Wait for Build and Deploy Workflow
        run: sleep 100

      - name: Trigger Deploy Cloud Run Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: deploy-cloud-run.yml
          token: ${{ secrets.PAT_TOKEN }}

      - name: Wait for Build and Deploy Workflow
        run: sleep 50
  