name: Test and Coverage HU03 finished

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
   test_and_coverage_sellers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r sellers-management/src/requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest sellers-management/tests --cov=sellers-management/src --cov-report=xml --cov-fail-under=80

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-authentications
          path: sellers-management/coverage.xml
